spring.application.name=dripverse_be

spring.datasource.url=jdbc:mysql://localhost:3306/dripverse?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwtSecret=DripverseSecretKeyThatIsVeryLongAndSecureForHS512Algorithm1234567890
app.jwtExpirationInMs=604800000